### ISSUE TITLE
Input off-by-one?

### ISSUE THREAD

**Issue by GregoryHlavac** [opiopan/simhid-g1000#4]
On left-side board to start the topmost tactile button is labeled SW2 but comes through the FSmapper application as SW1, is this an actual problem or just a misconfiguration on display somewhere?

**Comment by opiopan** [comment]
That is right behavior. 
I renamed the two lever switches labeled SW1 and SW27 on PCB to AUX1 and AUX2 when I wrote firmaware codes.
So, tactile switch numbers are rearranged 1 to 32.

**Comment by GregoryHlavac** [comment]
Ah, thanks.
