### ISSUE TITLE
Wrong dual encoder part number?

### ISSUE THREAD

**Issue by Drachenkaetzchen** [opiopan/simhid-g1000#7]
The documentation refers to `PEC11D-4120F-20015` which seems not to be a valid part number. `PEC11D-4120F-S0015` seems to be the proper one, is that correct?

**Comment by opiopan** [comment]
Thank you for reporting the mistake in the document. As you correctly pointed out, `PEC11D-4120F-S0015` is correct.
I will fix this mistake.

**Comment by Drachenkaetzchen** [comment]
Thank you for the fix! Looking forward building this project!
